# Generated by Django 4.2.5 on 2023-09-25 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Ідентифікатор проекту')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('cost_PDV', models.CharField(max_length=255, null=True, verbose_name='Вартість рейсу з ПДВ (вручну)')),
                ('count_trip', models.CharField(max_length=255, null=True, verbose_name='Кількість рейсів')),
                ('delivery_where', models.CharField(max_length=255, verbose_name='Доставка окремо/в ціні')),
                ('distance', models.CharField(max_length=255, null=True, verbose_name='Відстань, км')),
                ('tn_per_trip', models.CharField(max_length=255, null=True, verbose_name='ТН/рейс')),
                ('is_delivery', models.CharField(max_length=255, verbose_name='З/Без доставка')),
                ('guide_option', models.CharField(max_length=255, null=True, verbose_name='Реквізити')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('article', models.IntegerField(verbose_name='Артикул')),
                ('count', models.IntegerField(verbose_name='Кількість')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Знижка')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='calc.project')),
            ],
        ),
    ]
